{{- if and .Values.global.hubble.tls.auto.enabled (eq .Values.global.hubble.tls.auto.method "cronJob") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hubble-generate-certs
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - create
      - update
{{- end }}